spring:
  datasource:
    url: jdbc:tc:mysql:8.0.36:///core?useInformationSchema=true&user=root&password=test
    username: root
    password: test
  liquibase:
    change-log: classpath:/db/changelog/transfer/db.changelog-initial-schema.yaml
