spring:
  autoconfigure:
    exclude: org.springframework.boot.security.autoconfigure.actuate.web.servlet.ManagementWebSecurityAutoConfiguration
  datasource:
    url: jdbc:tc:mysql:8.0.36:///aggregate?useInformationSchema=true&user=root&password=test&TC_INITSCRIPT=db/init/01-init.sql
    username: root
    password: test
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - beans
auth:
  token:
    salt: remittance-token-salt
    access-expires-in: ${AUTH_TOKEN_ACCESS_EXPIRES_IN:3600}
    refresh-expires-in: ${AUTH_TOKEN_REFRESH_EXPIRES_IN:604800}
transfer:
  idempotency-key:
    expires-in: 24h

logging:
  level:
    org.testcontainers: DEBUG
    org.testcontainers.jdbc: DEBUG
