spring:
  datasource:
    url: jdbc:tc:mysql:8.0.36:///aggregate
    username: aggregate
    password: aggregate
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
auth:
  token:
    salt: remittance-token-salt
    access-expires-in: ${AUTH_TOKEN_ACCESS_EXPIRES_IN:3600}
    refresh-expires-in: ${AUTH_TOKEN_REFRESH_EXPIRES_IN:604800}
