services:
  mysql:
    container_name: mysql-member
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: member
      MYSQL_USER: member
      MYSQL_PASSWORD: member
      MYSQL_ROOT_PASSWORD: root
