[versions]

[plugins]
build-recipe = { id = "com.linecorp.build-recipe-plugin", version = "1.1.1" }
spring-boot = { id = "org.springframework.boot", version = "4.0.1" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }

[libraries]
