[versions]
jspecify = "1.0.0"
jjwt = "0.13.0"

[plugins]
build-recipe = { id = "com.linecorp.build-recipe-plugin", version = "1.1.1" }
spring-boot = { id = "org.springframework.boot", version = "4.0.1" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }

[libraries]
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
