spring:
  docker:
    compose:
      file: classpath:docker-compose.yml
      lifecycle-management: start-and-stop
  datasource:
    url: jdbc:mysql://localhost:3306/account
    username: account
    password: account
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
