services:
  mysql:
    container_name: mysql-account
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: account
      MYSQL_USER: account
      MYSQL_PASSWORD: account
      MYSQL_ROOT_PASSWORD: root
