services:
  mysql:
    container_name: mysql-ledger
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: ledger
      MYSQL_USER: ledger
      MYSQL_PASSWORD: ledger
      MYSQL_ROOT_PASSWORD: root
