services:
  mysql:
    container_name: mysql-aggregate
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: aggregate
      MYSQL_USER: aggregate
      MYSQL_PASSWORD: aggregate
      MYSQL_ROOT_PASSWORD: root

  rabbitmq:
      container_name: rabbitmq-aggregate
      image: rabbitmq:3.8.19
      ports:
      - "5672:5672"
      - "15672:15672"
